services:
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: "pg_isready -U ${DB_USER} --dbname=${DB_NAME}"
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_volume:
